services:
    db:
        image: postgres:16.2
        restart: always
        volumes:
            - ./data/db:/var/lib/postgresql/data
        environment:
            - POSTGRES_DB=postgres
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
    
    cache:
        image: redis:7.2.4
        restart: always
        volumes:
            - ./data/cache:/data
            
    web:
        image: ${DOCKERHUB_USERNAME}/gymstat-web:${TAG}
        command: ["./wait-for-it.sh", "db:5432", "--", "uwsgi", "--ini", "/code/config/uwsgi/uwsgi.ini"]
        restart: always
        volumes:
            - ./config/uwsgi:/code/config/uwsgi
            - uwsgi_socket:/run/uwsgi
            - static_volume:/code/static
            - media_volume:/code/media
            - ./fixtures:/fixtures
        environment:
            - DJANGO_SETTINGS_MODULE=gymstat.settings.prod
            - POSTGRES_DB=postgres
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
            - EMAIL_HOST_USER=${EMAIL_HOST_USER}
            - EMAIL_HOST_PASSWORD=${EMAIL_HOST_PASSWORD}
            - DEFAULT_FROM_EMAIL=${DEFAULT_FROM_EMAIL}
        depends_on:
            - db
            - cache
        
    nginx:
        image: ${DOCKERHUB_USERNAME}/gymstat-nginx:${TAG}
        restart: always
        volumes:
            - uwsgi_socket:/run/uwsgi:ro
            - /etc/letsencrypt:/etc/letsencrypt:ro
            - static_volume:/code/static:ro
            - media_volume:/code/media:ro
        ports:
            - "80:80"
            - "443:443"

volumes:
    uwsgi_socket:
    static_volume:
    media_volume: