services:
    db:
        image: postgres:16.2
        restart: always
        volumes:
            - ./data/db:/var/lib/postgresql/data
        environment:
            - POSTGRES_DB=postgres
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
    
    cache:
        image: redis:7.2.4
        restart: always
        volumes:
            - ./data/cache:/data
            
    web:
        build: ./gymstat
        command: ["./gymstat/wait-for-it.sh", "db:5432", "--", "uwsgi", "--ini", "/code/config/uwsgi/uwsgi.ini"]
        restart: always
        volumes:
            - ./gymstat:/code/gymstat
            - ./config:/code/config
        environment:
            - DJANGO_SETTINGS_MODULE=gymstat.settings.prod
            - POSTGRES_DB=postgres
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
        depends_on:
            - db
            - cache
        
    nginx:
        image: nginx:1.25.5
        restart: always
        volumes:
            - ./config/nginx:/etc/nginx/templates
            - ./gymstat:/code/gymstat
            - ./frontend:/code/frontend
            - /etc/letsencrypt:/etc/letsencrypt:ro
        ports:
            - "80:80"
            - "443:443"