NOTES_FIELDS = ["Text", "Datetime", "Duration", "Number", "5stars", "10stars"]
ALLOWED_EXERCISE_FIELDS = {
    "sets": "int",
    "reps": "int",
    "weight": ["float", ["kg", "lbs"]],
    "time": "duration",
    "distance": ["float", ["m", "km", "mi"]],
    "speed": ["float", ["kph", "mph", "mps"]],
    "rounds": "int",
    "rest": "duration",
    "rpe": "int",
    "attempts": "int",
    "successes": "int",
    "notes": "text",
    "tempo": "text",
}
ALLOWED_EXERCISE_TAGS = {
    "chest",
    "biceps",
    "cardio",
    "cycling",
    "running",
    "free weight",
    "machine",
    "triceps",
    "legs",
    "back",
    "shoulders",
    "abs",
    "core",
    "HIIT",
    "yoga",
    "pilates",
}
