# Generated by Django 5.1.4 on 2025-03-28 14:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("body_metrics", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="record",
            options={"ordering": ["-datetime"]},
        ),
        migrations.RemoveIndex(
            model_name="record",
            name="body_metric_datetim_23cfcb_idx",
        ),
        migrations.AddIndex(
            model_name="record",
            index=models.Index(
                fields=["-datetime"], name="body_metric_datetim_67b92d_idx"
            ),
        ),
    ]
