# Generated by Django 5.1.4 on 2025-03-30 12:08

import django.contrib.postgres.indexes
import django.db.models.deletion
import training.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ExerciseTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                (
                    "fields",
                    models.JSONField(
                        validators=[training.models.validate_fields]
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("is_admin", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("edited_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exercise_templates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Training",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("conducted", models.DateTimeField()),
                (
                    "title",
                    models.CharField(blank=True, max_length=70, null=True),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("score", models.PositiveIntegerField(default=10)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trainings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-conducted"],
            },
        ),
        migrations.CreateModel(
            name="Exercise",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveIntegerField()),
                ("data", models.JSONField()),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exercises",
                        to="training.exercisetemplate",
                    ),
                ),
                (
                    "training",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exercises",
                        to="training.training",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="TrainingTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=70)),
                ("description", models.TextField(blank=True, null=True)),
                ("data", models.JSONField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("edited_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="training_templates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.AddIndex(
            model_name="exercisetemplate",
            index=models.Index(
                fields=["is_active", "name"],
                name="training_ex_is_acti_dbae26_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="exercisetemplate",
            index=models.Index(
                fields=["is_active", "is_admin", "name"],
                name="training_ex_is_acti_aea247_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="exercisetemplate",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["fields"],
                name="exercise_templates_fields",
                opclasses=["jsonb_path_ops"],
            ),
        ),
        migrations.AddIndex(
            model_name="training",
            index=models.Index(
                fields=["-conducted"], name="training_tr_conduct_312bf2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="exercise",
            index=models.Index(
                fields=["training", "order"],
                name="training_ex_trainin_8465ce_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="exercise",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["data"],
                name="exercise_data",
                opclasses=["jsonb_path_ops"],
            ),
        ),
        migrations.AddIndex(
            model_name="trainingtemplate",
            index=models.Index(
                fields=["name"], name="training_tr_name_8468dc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="trainingtemplate",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["data"],
                name="training_template_data",
                opclasses=["jsonb_path_ops"],
            ),
        ),
    ]
