# Generated by Django 5.1.4 on 2025-04-11 12:36

import training.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("training", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="exercisetemplate",
            name="tags",
            field=models.JSONField(
                blank=True,
                null=True,
                validators=[
                    training.validators.validate_exercise_template_tags
                ],
            ),
        ),
    ]
