# Generated by Django 5.1.4 on 2025-02-22 12:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('training', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='exercisetype',
            name='bookmarked',
            field=models.ManyToManyField(blank=True, related_name='bookmarked_exercises', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='exercisetype',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_exercises', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='exercise',
            name='exercise_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exercises', to='training.exercisetype'),
        ),
        migrations.AddField(
            model_name='training',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trainings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='exercise',
            name='training',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='training.training'),
        ),
        migrations.AddIndex(
            model_name='training',
            index=models.Index(fields=['-conducted'], name='training_tr_conduct_312bf2_idx'),
        ),
        migrations.AddIndex(
            model_name='exercise',
            index=models.Index(fields=['order', 'suborder'], name='training_ex_order_aea187_idx'),
        ),
    ]
