# Generated by Django 5.1.3 on 2024-11-17 19:34

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='training',
            options={'ordering': ['-conducted']},
        ),
        migrations.RemoveIndex(
            model_name='training',
            name='training_tr_time_6dd23e_idx',
        ),
        migrations.RemoveField(
            model_name='training',
            name='time',
        ),
        migrations.AddField(
            model_name='training',
            name='conducted',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='training',
            index=models.Index(fields=['-conducted'], name='training_tr_conduct_312bf2_idx'),
        ),
    ]
