# Generated by Django 5.1.4 on 2025-03-07 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("training", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="exercisetype",
            name="bookmarked",
        ),
        migrations.RemoveField(
            model_name="exercisetype",
            name="private",
        ),
        migrations.AddField(
            model_name="exercisetype",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="exercisetype",
            name="iconColor",
            field=models.CharField(default="blue", max_length=8),
        ),
        migrations.AddField(
            model_name="exercisetype",
            name="iconId",
            field=models.IntegerField(default=1),
        ),
    ]
