# Generated by Django 5.1.4 on 2025-03-14 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("training", "0003_remove_exercisetype_bookmarked_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="training",
            name="duration",
        ),
        migrations.AddField(
            model_name="training",
            name="score",
            field=models.PositiveIntegerField(default=10),
        ),
    ]
