# Generated by Django 5.1.3 on 2024-11-29 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0004_exercisetype_subscribers_alter_exercisetype_owner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exercisetype',
            options={'ordering': ['name']},
        ),
    ]
