# Generated by Django 5.1.4 on 2025-05-28 05:32

import training.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("training", "0004_enable_pg_trgm"),
    ]

    operations = [
        migrations.AddField(
            model_name="training",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="trainingtemplate",
            name="data",
            field=models.JSONField(
                blank=True,
                default=dict,
                validators=[
                    training.validators.validate_training_template_data
                ],
            ),
        ),
    ]
