# Generated by Django 5.1.4 on 2025-03-26 07:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("training", "0004_remove_training_duration_training_score"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="exercisetype",
            index=models.Index(
                fields=["name", "base"], name="training_ex_name_44bc7a_idx"
            ),
        ),
    ]
