# Generated by Django 5.1.4 on 2025-05-28 05:33

import training.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("training", "0005_training_description_alter_trainingtemplate_data"),
    ]

    operations = [
        migrations.AlterField(
            model_name="training",
            name="notes",
            field=models.JSONField(
                blank=True,
                default=dict,
                validators=[training.validators.validate_training_notes],
            ),
        ),
    ]
