# Generated by Django 5.1.3 on 2024-11-29 19:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0005_alter_exercisetype_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercisetype',
            name='subscribers',
        ),
        migrations.AddField(
            model_name='exercisetype',
            name='base',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='exercisetype',
            name='bookmarked',
            field=models.ManyToManyField(blank=True, related_name='bookmarked_exercises', to=settings.AUTH_USER_MODEL),
        ),
    ]
