# Generated by Django 5.1.4 on 2025-05-28 06:12

import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("training", "0006_alter_training_notes"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="exercise",
            name="exercise_data",
        ),
        migrations.RemoveField(
            model_name="exercise",
            name="data",
        ),
        migrations.AddField(
            model_name="exercise",
            name="sets",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="exercise",
            name="units",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddIndex(
            model_name="exercise",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["units"],
                name="exercise_units",
                opclasses=["jsonb_path_ops"],
            ),
        ),
        migrations.AddIndex(
            model_name="exercise",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["sets"],
                name="exercise_sets",
                opclasses=["jsonb_path_ops"],
            ),
        ),
    ]
