# Generated by Django 5.1.3 on 2024-12-01 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0006_remove_exercisetype_subscribers_exercisetype_base_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='exercise_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exercises', to='training.exercisetype'),
        ),
    ]
