# Generated by Django 5.1.4 on 2025-05-30 07:17

import training.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "training",
            "0007_remove_exercise_exercise_data_remove_exercise_data_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="exercise",
            name="sets",
            field=models.JSONField(
                blank=True,
                default=list,
                validators=[training.validators.validate_exercise_sets],
            ),
        ),
        migrations.AlterField(
            model_name="exercise",
            name="units",
            field=models.JSONField(
                blank=True,
                default=dict,
                validators=[training.validators.validate_exercise_units],
            ),
        ),
    ]
