# Generated by Django 5.1.3 on 2024-12-09 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0007_exercise_exercise_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='suborder',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
