# Generated by Django 5.1.4 on 2025-05-30 07:23

import training.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("training", "0009_alter_exercise_sets_alter_exercise_units"),
    ]

    operations = [
        migrations.AlterField(
            model_name="training",
            name="notes",
            field=models.JSONField(
                blank=True,
                null=True,
                validators=[training.validators.validate_training_notes],
            ),
        ),
    ]
