# Generated by Django 5.1.3 on 2024-12-09 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0009_alter_exercise_suborder'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exercise',
            options={'ordering': ['order', 'suborder']},
        ),
    ]
