# Generated by Django 5.1.3 on 2024-12-27 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0010_alter_exercise_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exercise',
            options={'ordering': ['order']},
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='suborder',
        ),
    ]
