# Generated by Django 5.1.4 on 2025-01-20 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0011_alter_exercise_options_remove_exercise_suborder'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exercise',
            options={'ordering': ['order', 'suborder']},
        ),
        migrations.AddField(
            model_name='exercise',
            name='suborder',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='exercise',
            index=models.Index(fields=['order', 'suborder'], name='training_ex_order_aea187_idx'),
        ),
    ]
