# Generated by Django 5.1.4 on 2025-02-08 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0012_alter_exercise_options_exercise_suborder_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='duration',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='training',
            name='title',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='training',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
