name: Deploy to production

# Trigger the workflow when push to deploy branch
on:
  push:
    branches:
      - deploy
            
jobs:
  deploy:
    runs-on: ubuntu-latest
        
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.18'
      
      - name: Install dependencies and build Vite React
        working-directory: frontend/vite-react
        run: |
          npm ci
          npm run build
          
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
            
      - name: Deploy to production server
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} << 'EOF'
            cd ~/GymStat
            git pull origin deploy
            docker-compose up -d --build
          EOF